version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: test-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./mysql-dump:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=oms
        - MYSQL_USER=guest
        - MYSQL_PASSWORD=secret
      ports:
        - "4244:3306"

    webserver:
      image: nginx:alpine
      container_name: test-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "4242:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: test-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

          
    rabbitmq:
      image: "rabbitmq:3-management"
      container_name: test-rabbitmq
      hostname: "rabbit"
      ports:
        - "15672:15672"
        - "5672:5672"
      labels:
        NAME: "rabbitmq"
      volumes:
        - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config